### ISSUE TITLE
Test Current Limit mode for possible "Claw" to prevent burning out motor

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2018#14]
Past uses of a claw have used pneumatics which limits motion to two positions or motors that have limit switches to stop at open or closed position.  Investigate the potential of using current limit mode to have motor apply a fixed amount of force at any position but not burn out the motor when stalled.  This would be similar to what we did with the climbing motors last year which I believe really saved us a LOT of motor and gearbox problems.

**Comment by Shalmezad** [comment]
In addition to the normal current limiting we're used to (it's in the migration guide: https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/Migration%20Guide.md `configPeakCurrentLimit` and similar methods) they also have a closed loop current example we could potentially take a look at: https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/Java/CurrentClosedLoop/src/org/usfirst/frc/team217/robot/Robot.java#L72
