### ISSUE TITLE
Drone Drive - can' go full speed forward

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2018#16]
I think there is need for a little bit more math.  I don't see a way to go full speed forward.  Need some trig?

**Comment by Shalmezad** [comment]
May need to do something similar to what WPILib does for their arcade drive:
https://github.com/wpilibsuite/allwpilib/blob/0ef9803363380c58804a0d885a7cc7ea8233a1ac/wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotDrive.java#L402
This will need done for all the forward/turn drives (halo drive, drone drive, clayton drive, arcade drive)
