### ISSUE TITLE
Set Sensor Phase

### ISSUE THREAD

**Issue by Yand1** [The-Charge/PlyBot2018#31]

**Comment by sreeramsa** [comment]
If you want to take this job, go to
 http://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual.pdf
starting on page 49.

**Comment by AltesKathryn** [comment]
SetSenorDirection() can be used to keep the sensor and motor in phase for proper limit switch and closed loop features. This functions set the "Reverse Feedback Sensosr" signal.

In order for limit switches and closed-loop features to function correctly the sensor and motor has to be "in-phase". This means that the sensor position must move in a positive direction as the motor controller drives positive throttle
