### ISSUE TITLE
Configure Neutral Deadband

### ISSUE THREAD

**Issue by Yand1** [The-Charge/PlyBot2018#32]

**Comment by RALah** [comment]
Configure Neutral Deadband is supposed to delete distortion out of the oi reading. Hereby a deadband range value can be assigned..

//simplified pseudo-code
while(running) {
  if(Math.abs(getJoystickX()) >= someDeadbandValue)
    speed = getJoystickX;
  else
    speed = 0;
  driveSomewhere(speed)
}
