### ISSUE TITLE
Check that everyone has installed new Java libraries in Eclipse

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2018#40]

**Comment by JessicaKline** [comment]
- [x] Derek
- [x] Jessica
- [x] Kadeon
- [x] David
- [x] Ashwin
- [x] Nathaniel
- [ ] Kaylee
- [ ] Kathryn
- [ ] Caleb

- [ ] Programmer 3
- [ ] Programmer 4
- [ ] Programmer 5
