### ISSUE TITLE
Install new NavX libraries in Eclipse

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2018#41]
Looks like there was an update that came out on Jan 13th.  you can get llibraries here: https://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/

**Comment by JessicaKline** [comment]
- [x] Derek
- [x] Jessica
- [x] Kadeon
- [x] David
- [x] Ashwin
- [x] Nathaniel
- [ ] Kaylee
- [ ] Kathryn
- [ ] Caleb

- [ ] Programmer 3
- [ ] Programmer 4
- [ ] Programmer 5
