### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by Yand1** [The-Charge/PlyBot2018#49]
The elevator of our robot has a quadrature encoder and a motor. The elevator subsystem needs to be a PID subsystem. Some commands that are needed include setting the elevator to preset positions using a buttonbox, and adjusting the elevator position manually using an an axis.

**Comment by ghost** [comment]
The PID values still need to be tuned. However, this cannot be done until the robot is complete. The code may also need to be double checked as I haven't coded this type of PID controller before.
