### ISSUE TITLE
Measurements and angles for Auton

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/PlyBot2018#54]
Record in text files with format 5ft, 60dg, .... 
Make sure degrees are in absolute
please label what they are in the text files as well

**Comment by AshwinS27** [comment]
[https://docs.google.com/document/d/1fzN2kRO6Nbd4j0SLK5vM3wkvyKdMJSDA7ddYiTHRPpk/edit?usp=sharing](url)
Completed path for top and middle position.... bottom would be similar to the top
NOTE: For the link, if you simply click on it, it wont work; You need to copy and paste it

**Comment by JessicaKline** [comment]
Instead of labeling by top/bottom if it's not a huge hassle left and right would be preferable as that's what the FMS sends us to work with in the code. Left and right are from the drive station view point
