### ISSUE TITLE
Edit Photos

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/PlyBot2018#59]
Derek is going to need high quality photos of the field for his "game" for Auton selection.
Find a high quality picture of the top-view of the field. We only need about half the field. There will need to be four version with red/blue combinations representing everything

**Comment by ghost** [comment]
![frc field 2018 right](https://user-images.githubusercontent.com/25124534/35599039-dcc6cf1c-05f4-11e8-8625-3e4f43891e7c.png)
![frc field 2018 left](https://user-images.githubusercontent.com/25124534/35599040-dcdb4ae6-05f4-11e8-800e-fb5b61090aa3.png)

**Comment by JessicaKline** [comment]
Not quite what we need. There needs to be more of the scale, less blank space to the left and there needs to be all the combos of switch and scale.
