### ISSUE TITLE
List of What We Need Robot Time For

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/PlyBot2018#64]

**Comment by Kaedon2619** [comment]
- [ ] Autonomous Testing
- [ ] Test Elevator and Tune PID values
- [ ] Test TurnNDegrees and Tune PID values
- [ ] Test DriveXFeet and Tune PID values
- [ ] Test Collector

**Comment by JessicaKline** [comment]
- [ ] PID Tuning (longer project)
- [ ] - Motion Magic
- [ ] - TurnNDegreesAbsolute
- [ ] - TurnNDegreesRelative
- [ ] - Elevator
-ElevateToXPos
-Override/Limit Switches
-Current Limiting/MOTOR_POW
- [ ] - DriveXFeet
- [ ] - Shoulder
- [ ] - LockStraight
- [ ] Test All the Superstructure Things
- [ ] Test Auton Paths (longer project)
- [ ] Find new constants
- [ ] - TICKS_PER_FOOT
- [ ] - MAX_TICKS_PER_SEC
