### ISSUE TITLE
Hall Effect Logic

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/PlyBot2018#67]
The sensor for the elevator might be something called a Hall Effect. This senses ferrous metals as it goes past. Basically a single channel encoder - you get a blip every time the Hall Effect senses the metal. We need logic to keep track of the position of the elevator and the direction.

**Comment by Shalmezad** [comment]
Related helpful information:

[Using a counter](https://wpilib.screenstepslive.com/s/3120/m/7912/l/85635-using-counters)

**Comment by abcurrie** [comment]
The link you sent out was to 2014 code.  Here is a link to 2018 code.

 

It does not seem that the FRC code for a counter handles up and down counting by pulse width sensing.  I don’t think that the hall effect sensor that Bob Most was demonstrating supports this either.

 

I am wondering if it would be possible to use an encoder input  in 1x or 2x mode and to use the second (B)  channel connected to a digital output that we would program to change state depending on what direction the motor was running. 

 

Might be something to test on Plybot.

 

Sandy

**Comment by AshwinS27** [comment]
PseudoCode:
If beep then
______If motor speed > 0 then
__________height= +1
______Elseif motorspeed < 0 then
__________height= -1

//Can be reversed depending on motor wiring

**Comment by abcurrie** [comment]
Fixed some case problems with file names in Roberts Code.  

This now requires some testing.  The plan should be to use some digital inputs on the input channels and see if the the counters and encoders are giving any values.

For the counter on input channel four the counter should increment anytime the toggle switch is changes state.  Not sure if the switch will have problems with debouncing

For the encoder on channels 2,3  it will be need to be checked if the encoder increments when channel A is toggled.  It will need to be tested if the input value on channel B has any impact in whether the encoder counter goes up or down.  It might be possible that the encoder does not work at all.

**Comment by JessicaKline** [comment]
We can't see these changes on SourceTree. Could you push?

**Comment by abcurrie** [comment]
Strange?  I’ll see what I can find.

 

Sandy

**Comment by abcurrie** [comment]
Try looking for the branch testElevator2.  This should have to code I worked on

**Comment by abcurrie** [comment]
Look for the branch testElevator2.

sandy
