### ISSUE TITLE
Climber

### ISSUE THREAD

**Issue by Yand1** [The-Charge/PlyBot2018#71]
Make a theoretical climber with one motor.

**Comment by Kaedon2619** [comment]
Should this have a limit switch?

**Comment by ghost** [comment]
If a CANTalon does not change its power while a command is running then it only needs to be set once in the initialize of a command. (tested.)

**Comment by JessicaKline** [comment]
- [x] Change CAN-ID
- [x] Current Limiting

**Comment by ghost** [comment]
The most recent commit is missing the collector subsystems.

**Comment by ghost** [comment]
Finished and ready for merging, but is sounds like we will not be using it on the robot.
