### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2018#76]
How can the elevator issue be closed yet.  There is still testing to be done on the limit switch logic and resetting counters.

**Comment by ghost** [comment]
Pulled all issues connected to the elevator over to this issue.

- [x] Add Second Motor

- [x] Add Limit Switches

- [x] Add Final Variables for Tuning

- [x] Current Limit Elevator

**Comment by ghost** [comment]
Here is code that will read limit switch position

		elevator.getSensorCollection().isFwdLimitSwitchClosed()
                elevator.getSensorCollection().isRevLimitSwitchClosed() 

These methods can be use to determine if limit switches have been hit and to reset the counters
(Author: abcurrie)

**Comment by ghost** [comment]
I have a working version completed that can be tested.
