### ISSUE TITLE
Pokey Board Coding

### ISSUE THREAD

**Issue by JessicaKline** [The-Charge/PlyBot2018#83]
especially lighting up LEDs b/c a button was pressed.

**Comment by ghost** [comment]
[Button Box Old Version.zip](https://github.com/The-Charge/PlyBot2018/files/1738570/Button.Box.Old.Version.zip)

**Comment by AshwinS27** [comment]
[pokeygearbox.zip](https://github.com/The-Charge/PlyBot2018/files/1742355/pokeygearbox.zip)

**Comment by ghost** [comment]
[FINAL 2018 PokeyCode.zip](https://github.com/The-Charge/PlyBot2018/files/1777625/FINAL.2018.PokeyCode.zip)
